# Form implementation generated from reading ui file 'C:\Users\Admin\OneDrive\Documents\A\Do_an_tot_nghiep\giao_dien\dang_nhap.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 718)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 171, 161))
        self.label.setText("")
        self.label.setPixmap(
            QtGui.QPixmap(
                "C:\\Users\\Admin\\OneDrive\\Documents\\A\\Do_an_tot_nghiep\\giao_dien\\logo.png"
            )
        )
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 40, 541, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("font-weight: bold;")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(545, 140, 171, 41))
        self.label_3.setStyleSheet("font-weight: bold;")
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.user_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.user_name.setGeometry(QtCore.QRect(470, 330, 331, 31))
        self.user_name.setInputMask("")
        self.user_name.setText("")
        self.user_name.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.VisualMoveStyle)
        self.user_name.setObjectName("user_name")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 320, 61, 51))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setText("")
        self.label_4.setPixmap(
            QtGui.QPixmap(
                "C:\\Users\\Admin\\OneDrive\\Documents\\A\\Do_an_tot_nghiep\\giao_dien\\user_icon.png"
            )
        )
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 400, 61, 51))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setText("")
        self.label_5.setPixmap(
            QtGui.QPixmap(
                "C:\\Users\\Admin\\OneDrive\\Documents\\A\\Do_an_tot_nghiep\\giao_dien\\pw_icon.png"
            )
        )
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setGeometry(QtCore.QRect(470, 410, 331, 31))
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(410, 200, 551, 61))
        self.label_6.setStyleSheet("font-weight: bold;")
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(370, 300, 481, 231))
        self.frame.setStyleSheet(
            "background-color: rgb(170, 255, 255);\n"
            "background-color: rgba(170, 255, 255, 100);"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.dang_nhap = QtWidgets.QPushButton(parent=self.frame)
        self.dang_nhap.setGeometry(QtCore.QRect(190, 170, 141, 41))
        self.dang_nhap.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dang_nhap.setObjectName("dang_nhap")
        self.frame.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.user_name.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.password.raise_()
        self.label_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Đồ án tốt nghiệp"))
        self.label_3.setText(_translate("MainWindow", "Nhóm 53"))
        self.label_6.setText(
            _translate("MainWindow", "Quản lý hệ thống điện trong tòa nhà ")
        )
        self.dang_nhap.setText(_translate("MainWindow", "Đăng nhập"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
